package-name: airflow-provider-kuberay

display-name: Kuberay

docs-url: https://github.com/astronomer/airflow-provider-kuberay/blob/main/README.md

decorators:
  - module: ray.decorators.kuberay.ray_task

operators:
  - module: ray.operators.kuberay.RayClusterOperator
  - module: ray.operators.kuberay.SubmitRayJob

triggers:
  - module: ray.triggers.kuberay.RayJobTrigger
